version: "3"

services:
  node:
    build: ./backend
    depends_on:
      - sql
    env_file:
      # Make sure to update this to match your project.
      - ./autumnowl.env
    environment:
      - MYSQL_HOST=sql
    ports:
      - 8080:4200
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
  sql:
    build: ./sql
    platform: linux/x86_64
    # Make sure to update this to match your project.
    env_file:
      - ./autumnowl.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - compose-lesson:/var/lib/mysql
    ports:
      - 33006:3306
  app:
    build: ./frontend
    depends_on:
      - node
    #    For deploying to server use ports: - 80:80
    volumes:
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/autumnowl/etc/letsencrypt/live/autumnowl.design/fullchain.pem:/etc/letsencrypt/live/autumnowl.design/fullchain.pem
      - /docker-volumes/autumnowl/etc/letsencrypt/live/autumnowl.design/privkey.pem:/etc/letsencrypt/live/autumnowl.design/privkey.pemp-
    ports:
      - 80:80
      - 443:443
volumes:
  compose-lesson: